version: "3.7"

services:

  glibc-builder:
    build:
      context: .
      args:
        - version=2.30
        - build=dev
    image: leadstec/glibc-builder:2.30
    hostname: glibc-builder.local
    container_name: glibc-builder.local
